from app.db.models.actor_profile import ActorProfile
from app.db.models.agent import (
    AgentRecommendation,
    CareerMemory,
    CareerDevelopmentTask,
    CareerRecommendation,
    CareerSwotAnalysis,
    CareerTask,
    CastingGoal,
    ChiefOfStaffState,
    LearningInsight,
    ExecutiveBrief,
    MaterialGapAlert,
    OutcomeNudge,
    RecommendationFeedback,
    SelfTapeWorkflow,
    WatchList,
)
from app.db.models.automation import (
    DiscoverySettings,
    DiscoveryProviderSettings,
    DiscoveryRun,
    DiscoverySourcePlugin,
    SourceResearchItem,
    SubmissionAutomationQueue,
)
from app.db.models.asset import Archetype, Asset, AssetTag, asset_archetypes
from app.db.models.audit import ManualOverrideLog
from app.db.models.dashboard import DashboardWidget, FocusModePreference
from app.db.models.intelligence import (
    ActorRelationship,
    AuditionJournalEntry,
    AuditionPreparationBrief,
    CallbackEvent,
    CareerPathSimulation,
    CastingContact,
    CastingOffice,
    CommunicationLog,
    DreamRoleTarget,
    MaterialCreationPlan,
    QuarterlyCareerReview,
    RelationshipOpportunity,
    RelationshipSubmission,
    SceneCandidate,
    SelfTape,
    ScriptSource,
)
from app.db.models.journal import ActorJournalEntry
from app.db.models.opportunity import (
    BreakdownParseRun,
    BreakdownRole,
    BreakdownSection,
    CastingLanguage,
    CharacterProfile,
    Opportunity,
    OpportunitySource,
)
from app.db.models.operations import (
    AuditionCalendarEvent,
    AvailabilityBlock,
    CastingPlatformSubscription,
    DailyPlatformCheckIn,
    ProfessionalEquipmentProfile,
)
from app.db.models.platform import (
    PlatformAssetMapping,
    PlatformProfile,
    PublicProfileImport,
    SupervisedBreakdownImport,
)
from app.db.models.representation import ActingCredit, Representation
from app.db.models.submission import Submission, SubmissionAsset, SubmissionStatusHistory
from app.db.models.source_exclusion import SourceExclusion
from app.db.models.travel_preference import TravelPreference
from app.db.models.travel_estimate import TravelEstimate

__all__ = [
    "ActorProfile",
    "ActorRelationship",
    "ActorJournalEntry",
    "ActingCredit",
    "AgentRecommendation",
    "Archetype",
    "Asset",
    "AssetTag",
    "BreakdownRole",
    "BreakdownSection",
    "BreakdownParseRun",
    "CastingLanguage",
    "CharacterProfile",
    "AuditionCalendarEvent",
    "AuditionJournalEntry",
    "AuditionPreparationBrief",
    "AvailabilityBlock",
    "CareerPathSimulation",
    "CallbackEvent",
    "CastingContact",
    "CastingOffice",
    "CareerMemory",
    "CareerRecommendation",
    "CareerSwotAnalysis",
    "CareerDevelopmentTask",
    "CareerTask",
    "CastingGoal",
    "CastingPlatformSubscription",
    "ChiefOfStaffState",
    "DashboardWidget",
    "DailyPlatformCheckIn",
    "CommunicationLog",
    "ExecutiveBrief",
    "FocusModePreference",
    "DiscoveryRun",
    "DiscoverySettings",
    "DiscoveryProviderSettings",
    "DiscoverySourcePlugin",
    "DreamRoleTarget",
    "LearningInsight",
    "MaterialGapAlert",
    "MaterialCreationPlan",
    "ManualOverrideLog",
    "Opportunity",
    "OpportunitySource",
    "OutcomeNudge",
    "PlatformAssetMapping",
    "PlatformProfile",
    "ProfessionalEquipmentProfile",
    "PublicProfileImport",
    "QuarterlyCareerReview",
    "RecommendationFeedback",
    "Representation",
    "RelationshipOpportunity",
    "RelationshipSubmission",
    "SceneCandidate",
    "SelfTape",
    "ScriptSource",
    "SelfTapeWorkflow",
    "SourceResearchItem",
    "SourceExclusion",
    "SupervisedBreakdownImport",
    "Submission",
    "SubmissionAutomationQueue",
    "SubmissionAsset",
    "SubmissionStatusHistory",
    "TravelPreference",
    "TravelEstimate",
    "WatchList",
    "asset_archetypes",
]
