import { queryStaleTimes } from "./queryPolicy";

export type QueryPolicyClass = "live" | "workflow" | "reference" | "configuration" | "derived";

export type QueryPolicyInventoryEntry = {
  family: string;
  owner: string;
  endpoints: readonly string[];
  consumers: readonly string[];
  classification: QueryPolicyClass;
  staleTime: number;
  gcTime: number;
  refetchOnMount: "always" | "stale" | false;
  refetchOnReconnect: true;
  refetchOnFocus: false;
  volatility: string;
  invalidation: string;
  staleConsequence: string;
  requestConsequence: string;
};

const shared = { gcTime: 10 * 60_000, refetchOnReconnect: true as const, refetchOnFocus: false as const };

export const queryPolicyInventory: readonly QueryPolicyInventoryEntry[] = [
  { family: "system.capabilities", owner: "system", endpoints: ["/system/capabilities"], consumers: ["app shell", "Settings", "Script Finder"], classification: "configuration", staleTime: queryStaleTimes.configuration, refetchOnMount: false, volatility: "provider changes only", invalidation: "provider/settings mutations", staleConsequence: "temporarily outdated availability labels", requestConsequence: "entry-graph request on every mount", ...shared },
  { family: "chief.commandCenter", owner: "chief-of-staff", endpoints: ["/command-center"], consumers: ["Dashboard", "Calendar"], classification: "live", staleTime: queryStaleTimes.live, refetchOnMount: "always", volatility: "deadlines, queues, check-ins", invalidation: "check-in, nudge, refresh mutations", staleConsequence: "missed operational priority", requestConsequence: "one operational snapshot request", ...shared },
  { family: "calendar.events", owner: "calendar", endpoints: ["/operations/calendar/events"], consumers: ["Calendar", "Dashboard"], classification: "live", staleTime: queryStaleTimes.live, refetchOnMount: "always", volatility: "audition deadlines and callbacks", invalidation: "Calendar mutations and synchronous submission/breakdown creation; derived owner projections invalidate their owner keys", staleConsequence: "incorrect deadline display", requestConsequence: "one event-list request", ...shared },
  { family: "calendar.availability", owner: "calendar", endpoints: ["/operations/availability"], consumers: ["Calendar"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "always", volatility: "manual and external schedule changes", invalidation: "availability mutations", staleConsequence: "incorrect availability", requestConsequence: "one availability-list request", ...shared },
  { family: "dashboard.preferences", owner: "dashboard", endpoints: ["/dashboard/widgets", "/dashboard/focus-mode"], consumers: ["Dashboard"], classification: "configuration", staleTime: queryStaleTimes.configuration, refetchOnMount: "stale", volatility: "user settings", invalidation: "widget/focus mutations", staleConsequence: "briefly old layout preference", requestConsequence: "two redundant configuration requests", ...shared },
  { family: "profile.stable", owner: "profile", endpoints: ["/actor-profile", "/representation", "/representation/acting-credits/list", "/travel-preferences/{id}", "/operations/equipment-profile", "/operations/platform-subscriptions", "/platform-imports/asset-mappings"], consumers: ["Profile", "Breakdowns", "Auditions", "Calendar", "Journal"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "stale", volatility: "user mutations", invalidation: "focused Profile mutations on shared public keys", staleConsequence: "briefly old option label", requestConsequence: "up to seven redundant requests", ...shared },
  { family: "profile.imports", owner: "profile", endpoints: ["/platform-imports/profiles", "/platform-imports/public-profiles"], consumers: ["Profile"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "always", volatility: "import processing may finish externally", invalidation: "import actions", staleConsequence: "import status appears stuck", requestConsequence: "two import status requests", ...shared },
  { family: "materials.assets", owner: "materials", endpoints: ["/assets"], consumers: ["Materials", "Profile", "Journal", "Breakdowns", "Auditions"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "stale", volatility: "user material mutations", invalidation: "material mutations on one shared public key", staleConsequence: "briefly old material option", requestConsequence: "repeated shared asset request", ...shared },
  { family: "materials.reusableTapes", owner: "materials", endpoints: ["/intelligence/self-tapes"], consumers: ["Materials"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "stale", volatility: "user tape mutations", invalidation: "reusable-tape mutations", staleConsequence: "briefly old reusable tape", requestConsequence: "redundant library request", ...shared },
  { family: "materials.reusableAnalytics", owner: "materials", endpoints: ["/intelligence/self-tapes/analytics"], consumers: ["Materials"], classification: "derived", staleTime: queryStaleTimes.reference, refetchOnMount: "stale", volatility: "changes with reusable tapes", invalidation: "all reusable-tape mutations", staleConsequence: "briefly old aggregate", requestConsequence: "recomputes unchanged aggregate", ...shared },
  { family: "relationships.records", owner: "relationships", endpoints: ["/intelligence/relationships", "/intelligence/relationships/analytics", "/intelligence/communication-logs"], consumers: ["Relationships", "Dashboard", "Career"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "stale", volatility: "user relationship mutations", invalidation: "relationship and communication mutations", staleConsequence: "briefly old relationship data", requestConsequence: "three redundant requests", ...shared },
  { family: "analytics.operational", owner: "analytics", endpoints: ["/operations/dashboard"], consumers: ["Analytics", "Dashboard"], classification: "live", staleTime: queryStaleTimes.live, refetchOnMount: "always", volatility: "deadlines and cost outcomes", invalidation: "explicit Calendar and submission cost/lifecycle contracts; external changes remain", staleConsequence: "incorrect operational summary", requestConsequence: "derived dashboard request", ...shared },
  { family: "analytics.derived", owner: "analytics", endpoints: ["/intelligence/dashboard", "/intelligence/materials/performance"], consumers: ["Analytics", "Dashboard", "Career"], classification: "derived", staleTime: queryStaleTimes.workflow, refetchOnMount: "stale", volatility: "submissions, outcomes, materials, opportunities, recommendations", invalidation: "Step 47/48 explicit submission, callback, material, opportunity, and recommendation contracts", staleConsequence: "up to one minute of old career/performance insight outside this tab", requestConsequence: "two aggregate computations avoided on fresh immediate return", ...shared },
  { family: "analytics.industryTrends", owner: "analytics", endpoints: ["/intelligence/casting-patterns"], consumers: ["Analytics", "Dashboard", "Career"], classification: "reference", staleTime: queryStaleTimes.reference, refetchOnMount: "stale", volatility: "changes only with accumulated history", invalidation: "stale-time plus relevant route refresh", staleConsequence: "temporarily old trend", requestConsequence: "unnecessary aggregate calculation", ...shared },
  { family: "auditions.workflow", owner: "auditions", endpoints: ["/submissions", "/command-center/self-tapes", "/intelligence/callback-events", "/intelligence/audition-journal"], consumers: ["Auditions", "Calendar", "Dashboard", "Materials"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "always", volatility: "deadlines and external outcomes", invalidation: "explicit submission/callback/self-tape contracts; external outcomes remain", staleConsequence: "missed audition status", requestConsequence: "four workflow requests", ...shared },
  { family: "breakdowns.workflow", owner: "breakdowns", endpoints: ["/opportunities", "/automation/opportunities/hidden", "/agents/recommendations", "/automation/submission-queue", "/intelligence/readiness/opportunities"], consumers: ["Breakdowns", "Auditions", "Calendar", "Dashboard"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "always", volatility: "discovery and queue execution", invalidation: "focused discovery/classification/queue mutations", staleConsequence: "missed opportunity or queue state", requestConsequence: "parallel workflow requests", ...shared },
  { family: "journal.entries", owner: "journal", endpoints: ["/journal"], consumers: ["Journal"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "stale", volatility: "synchronously generated by actor-work workflows", invalidation: "Step 47 explicit submission, callback, self-tape, material, Career-task, breakdown, and check-in contracts cover every ActorWorkEventService caller", staleConsequence: "up to one minute of old history after an out-of-tab write", requestConsequence: "one history request avoided on fresh immediate return", ...shared },
  { family: "career.records", owner: "career-intelligence", endpoints: ["/career-development/tasks", "/agents/career/swot", "/intelligence/career/quarterly-reviews", "/agents/casting-goals", "/agents/watch-lists", "/agents/career-memory"], consumers: ["Career", "Dashboard", "Journal"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "always", volatility: "tasks may change through material workflows", invalidation: "explicit Career-task, goal/watch-list, and material-link contracts; agent generation lacks completion status", staleConsequence: "incorrect task progress", requestConsequence: "multiple workflow requests", ...shared },
  { family: "sourceLibrary.records", owner: "source-library", endpoints: ["/automation/source-research", "/automation/source-research/archive"], consumers: ["Source Library", "Breakdowns", "Dashboard"], classification: "workflow", staleTime: queryStaleTimes.workflow, refetchOnMount: "always", volatility: "discovery runs and health checks", invalidation: "source and discovery mutations", staleConsequence: "new research omitted", requestConsequence: "source list requests", ...shared },
  { family: "scriptFinder.sources", owner: "script-finder", endpoints: ["/intelligence/scripts/sources"], consumers: ["Career Script Finder"], classification: "reference", staleTime: queryStaleTimes.reference, refetchOnMount: "stale", volatility: "user-managed source catalog", invalidation: "script-source creation", staleConsequence: "briefly old source option", requestConsequence: "StrictMode duplicate without Query deduplication", ...shared }
] as const;
