export const genderIdentityOptions = [
  "Woman",
  "Man",
  "Nonbinary",
  "Trans Woman",
  "Trans Man",
  "Trans",
  "Two-Spirit",
  "Gender Nonconforming",
  "Genderqueer",
  "Agender",
  "Questioning",
  "Prefer to self-describe"
];

export const genderExpressionOptions = [
  "Feminine",
  "Masculine",
  "Androgynous",
  "Gender Nonconforming",
  "Neutral",
  "Flexible / Range",
  "Prefer to self-describe"
];

export const pronounOptions = [
  "she/her",
  "he/him",
  "they/them",
  "she/they",
  "he/they",
  "any pronouns",
  "prefer name only",
  "prefer to self-describe"
];

export const ethnicityOptions = [
  "Hispanic or Latino",
  "Not Hispanic or Latino",
  "Latine",
  "Latina",
  "Latino",
  "Mexican",
  "Puerto Rican",
  "Cuban",
  "Dominican",
  "Central American",
  "South American",
  "Spanish",
  "Brazilian",
  "Caribbean",
  "West Indian",
  "African",
  "West African",
  "East African",
  "North African",
  "Prefer to self-describe"
];

export const raceIdentityOptions = [
  "American Indian or Alaska Native",
  "Asian",
  "Black or African American",
  "Hispanic or Latino",
  "Middle Eastern or North African",
  "Native Hawaiian or Pacific Islander",
  "White",
  "Two or More Races",
  "Multiracial",
  "Biracial",
  "Afro-Latine",
  "Asian American",
  "South Asian",
  "East Asian",
  "Southeast Asian",
  "Pacific Islander",
  "Indigenous",
  "Some Other Race",
  "Prefer to self-describe"
];

export const nationalityOptions = [
  "American",
  "African American",
  "Afro-Caribbean",
  "Barbadian",
  "Bahamian",
  "Brazilian",
  "British",
  "Cameroonian",
  "Canadian",
  "Chinese",
  "Colombian",
  "Cuban",
  "Dominican",
  "Ethiopian",
  "French",
  "Ghanaian",
  "Haitian",
  "Indian",
  "Irish",
  "Italian",
  "Jamaican",
  "Japanese",
  "Kenyan",
  "Korean",
  "Liberian",
  "Mexican",
  "Nigerian",
  "Puerto Rican",
  "Sierra Leonean",
  "South African",
  "Spanish",
  "Trinidadian and Tobagonian",
  "Vietnamese",
  "Prefer to self-describe"
];

export const languageOptions = [
  "English",
  "Spanish",
  "French",
  "Portuguese",
  "Arabic",
  "Mandarin Chinese",
  "Cantonese",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Tagalog",
  "Hindi",
  "Urdu",
  "Bengali",
  "Punjabi",
  "Russian",
  "German",
  "Italian",
  "Greek",
  "Hebrew",
  "Yiddish",
  "American Sign Language",
  "Haitian Creole",
  "Swahili",
  "Yoruba",
  "Igbo",
  "Twi",
  "Wolof",
  "Krio",
  "Mende",
  "Temne",
  "Fula",
  "Prefer to self-describe"
];

export const accentOptions = [
  "Standard American",
  "General American",
  "New York",
  "Boston",
  "Southern American",
  "Midwestern American",
  "California",
  "British RP",
  "Cockney",
  "Irish",
  "Scottish",
  "French",
  "Spanish",
  "Italian",
  "German",
  "Russian",
  "Middle Eastern",
  "African",
  "West African",
  "East African",
  "Caribbean",
  "Jamaican",
  "Haitian",
  "Nigerian",
  "Ghanaian",
  "Sierra Leonean",
  "South African",
  "Indian",
  "Chinese",
  "Korean",
  "Japanese",
  "Filipino",
  "Prefer to self-describe"
];

export const disabilityIdentityOptions = [
  "Disabled",
  "Deaf",
  "Hard of Hearing",
  "Blind",
  "Low Vision",
  "Wheelchair User",
  "Mobility Disability",
  "Neurodivergent",
  "Autistic",
  "ADHD",
  "Chronic Illness",
  "Mental Health Disability",
  "Prefer to self-describe"
];
